// <auto-generated />
using System;
using FortuneWheel.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FortuneWheel.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240120123108_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FortuneWheel.Domain.Auth.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FortuneWheel.Domain.Auth.UnconfirmedEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnconfirmedEmails");
                });

            modelBuilder.Entity("FortuneWheel.Domain.Segments.Segment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassicWheelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("HexColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassicWheelId");

                    b.ToTable("Segments");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Segment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FortuneWheel.Domain.WheelsOfFortune.ClassicWheel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ClassicWheels");
                });

            modelBuilder.Entity("FortuneWheel.Domain.WheelsOfFortune.PointWheel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("PointWheels");
                });

            modelBuilder.Entity("FortuneWheel.Domain.Segments.PointSegment", b =>
                {
                    b.HasBaseType("FortuneWheel.Domain.Segments.Segment");

                    b.Property<Guid?>("PointWheelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("PointWheelId");

                    b.HasDiscriminator().HasValue("PointSegment");
                });

            modelBuilder.Entity("FortuneWheel.Domain.Segments.Segment", b =>
                {
                    b.HasOne("FortuneWheel.Domain.WheelsOfFortune.ClassicWheel", null)
                        .WithMany("Segments")
                        .HasForeignKey("ClassicWheelId");
                });

            modelBuilder.Entity("FortuneWheel.Domain.Segments.PointSegment", b =>
                {
                    b.HasOne("FortuneWheel.Domain.WheelsOfFortune.PointWheel", null)
                        .WithMany("Segments")
                        .HasForeignKey("PointWheelId");
                });

            modelBuilder.Entity("FortuneWheel.Domain.WheelsOfFortune.ClassicWheel", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("FortuneWheel.Domain.WheelsOfFortune.PointWheel", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
