// <auto-generated />
using System;
using WheelOfFortune.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WheelOfFortune.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240222091720_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FortuneWheel.Domain.Auth.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FortuneWheel.Domain.Auth.UnconfirmedEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnconfirmedEmails");
                });

            modelBuilder.Entity("FortuneWheel.Domain.Segments.Segment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassicWheelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassicWheelId");

                    b.ToTable("Segments", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("FortuneWheel.Domain.WheelsOfFortune.ClassicWheel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ClassicWheels");
                });

            modelBuilder.Entity("FortuneWheel.Domain.WheelsOfFortune.PointWheel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("PointWheels");
                });

            modelBuilder.Entity("FortuneWheel.Domain.Segments.PointSegment", b =>
                {
                    b.HasBaseType("FortuneWheel.Domain.Segments.Segment");

                    b.Property<Guid?>("PointWheelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Points")
                        .HasColumnType("bigint");

                    b.HasIndex("PointWheelId");

                    b.ToTable("PointSegments", (string)null);
                });

            modelBuilder.Entity("FortuneWheel.Domain.Segments.Segment", b =>
                {
                    b.HasOne("FortuneWheel.Domain.WheelsOfFortune.ClassicWheel", null)
                        .WithMany("Segments")
                        .HasForeignKey("ClassicWheelId");
                });

            modelBuilder.Entity("FortuneWheel.Domain.Segments.PointSegment", b =>
                {
                    b.HasOne("FortuneWheel.Domain.Segments.Segment", null)
                        .WithOne()
                        .HasForeignKey("FortuneWheel.Domain.Segments.PointSegment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FortuneWheel.Domain.WheelsOfFortune.PointWheel", null)
                        .WithMany("Segments")
                        .HasForeignKey("PointWheelId");
                });

            modelBuilder.Entity("FortuneWheel.Domain.WheelsOfFortune.ClassicWheel", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("FortuneWheel.Domain.WheelsOfFortune.PointWheel", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
